#!/usr/bin/env python3
"""
Generate word_character_links.json from p1_words + p2_words + characters_1200.

Fully automatic: one link per lexicon word_id, characters[] = CJK graphemes in
headword order, character_id + hanzi from corpus (first match per hanzi).

Usage:
  python tools/generate_word_character_links.py          # dry-run, summary only
  python tools/generate_word_character_links.py --write  # overwrite word_character_links.json
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LINKS_PATH = ROOT / "word_character_links.json"
TEMPLATE_PATH = LINKS_PATH  # read for metadata blocks to preserve


def graphemes_cjk(hz: str) -> list[str]:
    out: list[str] = []
    for ch in hz.strip():
        o = ord(ch)
        if 0x4E00 <= o <= 0x9FFF or 0x3400 <= o <= 0x4DBF:
            out.append(ch)
    return out


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def load_characters_1200() -> tuple[list[dict], dict[str, dict]]:
    """Return (raw list, first row per hanzi). Same pick-largest as builder/audit."""
    best_blob: dict | None = None
    best_n = -1
    for p in (ROOT / "characters_1200.json", ROOT / "data" / "characters_1200.json"):
        if not p.is_file():
            continue
        try:
            blob = load_json(p)
        except (json.JSONDecodeError, OSError):
            continue
        if not isinstance(blob, dict):
            continue
        n = len(blob.get("characters") or [])
        if n > best_n:
            best_n = n
            best_blob = blob
    if not best_blob:
        raise FileNotFoundError("characters_1200.json not found (root or data/)")
    char_list = best_blob.get("characters") or []
    by_hanzi: dict[str, dict] = {}
    for c in char_list:
        hz = (c.get("hanzi") or "").strip()
        if hz and hz not in by_hanzi:
            by_hanzi[hz] = c
    return char_list, by_hanzi


def load_lexicon_words() -> list[tuple[str, str]]:
    """(word_id, primary_hanzi) sorted by word_id. p2 overrides p1 on duplicate id."""
    by_id: dict[str, str] = {}
    for name in ("p1_words.json", "p2_words.json"):
        p = ROOT / name
        if not p.is_file():
            continue
        data = load_json(p)
        for w in data.get("words", []):
            wid = w.get("id") or w.get("word_id")
            hz = w.get("hanzi")
            if not wid or hz is None:
                continue
            surface = str(hz).split("/")[0].strip()
            by_id[str(wid)] = surface
    return sorted(by_id.items(), key=lambda x: x[0])


def build_links(
    lexicon: list[tuple[str, str]], by_hanzi: dict[str, dict]
) -> tuple[list[dict], list[tuple[str, str, list[str]]]]:
    """
    Returns (links, problems) where problems are (word_id, hanzi, missing_graphemes).
    """
    links: list[dict] = []
    problems: list[tuple[str, str, list[str]]] = []
    auto_note = (
        "Auto-generated by tools/generate_word_character_links.py "
        "(semantic_core, default strength)."
    )

    for word_id, word_hanzi in lexicon:
        grams = graphemes_cjk(word_hanzi)
        if not grams:
            problems.append((word_id, word_hanzi, ["<no CJK in headword>"]))
            links.append(
                {
                    "word_id": word_id,
                    "word_hanzi": word_hanzi,
                    "characters": [],
                    "notes": auto_note + " No CJK graphemes in primary headword.",
                }
            )
            continue

        chars_out: list[dict] = []
        missing: list[str] = []
        n = len(grams)
        strength = round(0.85 if n == 1 else max(0.55, 0.9 - 0.08 * (n - 1)), 2)
        for g in grams:
            row = by_hanzi.get(g)
            if not row or not row.get("id"):
                missing.append(g)
                continue
            chars_out.append(
                {
                    "character_id": row["id"],
                    "hanzi": g,
                    "role": "semantic_core",
                    "strength": strength,
                }
            )

        if missing:
            problems.append((word_id, word_hanzi, missing))

        links.append(
            {
                "word_id": word_id,
                "word_hanzi": word_hanzi,
                "characters": chars_out,
                "notes": auto_note,
            }
        )

    return links, problems


def build_reverse_index(links: list[dict]) -> dict:
    rev: dict[str, dict] = {}
    for link in links:
        wid = link["word_id"]
        for c in link.get("characters") or []:
            cid = c.get("character_id")
            hz = c.get("hanzi")
            if not cid:
                continue
            if cid not in rev:
                rev[cid] = {"hanzi": hz, "word_ids": []}
            if wid not in rev[cid]["word_ids"]:
                rev[cid]["word_ids"].append(wid)
    for v in rev.values():
        v["word_ids"] = sorted(v["word_ids"])
    # stable key order
    return dict(sorted(rev.items(), key=lambda kv: kv[0]))


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate word_character_links from lexicon + corpus.")
    ap.add_argument(
        "--write",
        action="store_true",
        help=f"Write {LINKS_PATH.name} (preserves conventions + routing_rules from current file).",
    )
    args = ap.parse_args()

    lexicon = load_lexicon_words()
    if not lexicon:
        print("No words loaded from p1_words.json / p2_words.json", file=sys.stderr)
        return 1

    _, by_hanzi = load_characters_1200()
    links, problems = build_links(lexicon, by_hanzi)

    print(f"Lexicon words: {len(lexicon)}")
    print(f"Links built:   {len(links)}")
    print(f"Corpus hanzi:  {len(by_hanzi)}")
    if problems:
        print(f"Problems (missing corpus row for grapheme): {len(problems)}")
        for wid, hz, miss in problems[:30]:
            print(f"  {wid}  {hz!r}  missing: {miss}")
        if len(problems) > 30:
            print(f"  ... and {len(problems) - 30} more")
    else:
        print("All words: every CJK grapheme resolved in corpus.")

    if not args.write:
        print("\nDry-run only. Pass --write to update word_character_links.json.")
        return 0 if not problems else 2

    if not TEMPLATE_PATH.is_file():
        print(f"Missing {TEMPLATE_PATH}", file=sys.stderr)
        return 1

    template = load_json(TEMPLATE_PATH)
    out = {
        "schema_version": template.get("schema_version", "1.0"),
        "name": template.get("name", "Word–Character Link Index"),
        "description": template.get("description", ""),
        "conventions": template.get("conventions", {}),
        "links": links,
        "reverse_index": build_reverse_index(links),
        "routing_rules": template.get(
            "routing_rules",
            {
                "default": "word_first",
                "character_review_triggers": [],
                "srs_linkage": {},
            },
        ),
    }
    LINKS_PATH.write_text(
        json.dumps(out, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"\nWrote {LINKS_PATH.relative_to(ROOT)}")
    return 0 if not problems else 2


if __name__ == "__main__":
    raise SystemExit(main())
